baseURL = "https://vain0x.github.io/blog"
publishDir = "docs"
theme = "beautifulhugo"

title = "ベインのブログ"

languageCode = "ja-jp"
DefaultContentLanguage = "ja"

metaDataFormat = "yaml"

buildFuture = true

pygmentsCodeFences = true
pygmentsUseClasses = true

[Author]
name = "ベイン"
email = "vainzerox@gmail.com"
website = "https://vain0x.github.io"
github = "vain0x"
twitter = "vain0x"

[Params]
favicon = "https://vain0x.github.io/favicon.jpg"
rss = true
showRelatedPosts = true
since = 2016

[[menu.main]]
name = "GitHub"
url = "https://github.com/vain0x"
weight = 1

[[menu.main]]
name = "競プロ参戦記"
url = "https://qiita.com/search?q=%E7%AB%B6%E3%83%97%E3%83%AD%E5%8F%82%E6%88%A6%E8%A8%98+user%3Avain0x&sort=created"
weight = 2

[[menu.main]]
name = "ABOUT"
url = "https://vain0x.github.io"
weight = 3
